baseURL = "http://example.org/"
languageCode = "en-us"
title = "Taufiq Dhanani"
theme = "hugo-coder"


[params]
  author = "Taufiq Dhanani"
  info = "Software Engineer | Boston, MA"
  description = "Taufiq's personal website"
  keywords = "blog,developer,personal"
  #gravatar = "john.doe@example.com"

  footercontent = "Enter a text here."
  hideFooter = false
  hideCredits = false
  hideCopyright = false
  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/dhanani94"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/TaufiqDhanani"
[[params.social]]
  name = "Instagram"
  icon = "fa fa-instagram fa-2x"
  weight = 3
  url = "https://www.instagram.com/imtaufiq/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"